name: Release

on:
  push:
    tags:
      - "*"

jobs:
  call-build-workflow:
    if: "startsWith(github.ref, 'refs/tags')"
    uses: simowNgithub/evcc/.github/workflows/default.yml@master

  docker:
    name: Publish Docker :release
    needs:
      - call-build-workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: simowN/evcc

      - name: Publish
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: RELEASE=1
          tags: ${{ steps.meta.outputs.tags }}

      - name: Create Github Release
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          # use GH_TOKEN for access to evcc-io/homebrew-tap
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  hassio:
    name: Hassio Addon
    needs:
      - docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: simowNgithub/hassio-addon
          token: ${{ secrets.GH_TOKEN }}
          path: ./hassio

      - name: Update version
        run: |
          sed -i -e s#\"version.*#\"version\":\ \"$(echo ${{ github.ref }} | sed -e s#refs/tags/##)\",# ./hassio/evcc/config.json

      - name: Push
        run: |
          cd ./hassio
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Mirror evcc release"
          git push
